# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logregi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
    ]
